package com.tfg.tfg.dto;

import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * DTO for AI-powered performance analysis response.
 * Contains the analysis generated by Google Gemini AI based on player's match history.
 */
public class AiAnalysisResponseDto {
    
    private String analysis;
    
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime generatedAt;
    
    private int matchesAnalyzed;
    
    private String summonerName;
    
    public AiAnalysisResponseDto() {
    }
    
    public AiAnalysisResponseDto(String analysis, LocalDateTime generatedAt, int matchesAnalyzed, String summonerName) {
        this.analysis = analysis;
        this.generatedAt = generatedAt;
        this.matchesAnalyzed = matchesAnalyzed;
        this.summonerName = summonerName;
    }
    
    public String getAnalysis() {
        return analysis;
    }
    
    public void setAnalysis(String analysis) {
        this.analysis = analysis;
    }
    
    public LocalDateTime getGeneratedAt() {
        return generatedAt;
    }
    
    public void setGeneratedAt(LocalDateTime generatedAt) {
        this.generatedAt = generatedAt;
    }
    
    public int getMatchesAnalyzed() {
        return matchesAnalyzed;
    }
    
    public void setMatchesAnalyzed(int matchesAnalyzed) {
        this.matchesAnalyzed = matchesAnalyzed;
    }
    
    public String getSummonerName() {
        return summonerName;
    }
    
    public void setSummonerName(String summonerName) {
        this.summonerName = summonerName;
    }
}
