package com.tfg.tfg.model.dto;

import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for AI-powered performance analysis response.
 * Contains the analysis generated by Google Gemini AI based on player's match history.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class AiAnalysisResponseDto {
    
    private String analysis;
    
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime generatedAt;
    
    private int matchesAnalyzed;
    
    private String summonerName;
    
}
